<h1>Goals and locations</h1>
<div class="grid two">
<section class="card"><h2>Add goal</h2><form method="post" action="/admin/catalogs/goals"><?= csrf_field() ?><label>Title <input name="title" required></label><label>Description <textarea name="description"></textarea></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save goal</button></form></section>
<section class="card"><h2>Add province/state</h2><form method="post" action="/admin/catalogs/provinces"><?= csrf_field() ?><label>Name <input name="name" required></label><label>Country code <input name="country_code" value="US" maxlength="2"></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save province</button></form></section>
</div>
<section class="card"><h2>Add city</h2><form method="post" action="/admin/catalogs/cities" class="grid two"><?= csrf_field() ?><label>Province <select name="province_id" required><?php foreach ($provinces as $province): ?><option value="<?= (int)$province['id'] ?>"><?= e($province['name']) ?></option><?php endforeach; ?></select></label><label>Name <input name="name" required></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save city</button></form></section>
<div class="grid two">
<section class="card table-wrap"><h2>Goals</h2><table><thead><tr><th>Title</th><th>Description</th><th>Sort</th><th>Active</th><th></th></tr></thead><tbody><?php foreach ($goals as $goal): ?><tr><form method="post" action="/admin/catalogs/goals"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$goal['id'] ?>"><td><input name="title" value="<?= e($goal['title']) ?>" required></td><td><input name="description" value="<?= e($goal['description']) ?>"></td><td><input type="number" name="sort_order" value="<?= (int)$goal['sort_order'] ?>"></td><td><input type="checkbox" name="is_active" value="1" <?= $goal['is_active'] ? 'checked' : '' ?>></td><td><button>Update</button></form><form class="inline" method="post" action="/admin/catalogs/goals/delete" onsubmit="return confirm('Disable this goal?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$goal['id'] ?>"><button>Disable</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card table-wrap"><h2>Cities</h2><table><thead><tr><th>City</th><th>Province</th><th>Sort</th><th>Active</th><th></th></tr></thead><tbody><?php foreach ($cities as $city): ?><tr><form method="post" action="/admin/catalogs/cities"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$city['id'] ?>"><td><input name="name" value="<?= e($city['name']) ?>" required></td><td><select name="province_id" required><?php foreach ($provinces as $province): ?><option value="<?= (int)$province['id'] ?>" <?= (int)$city['province_id'] === (int)$province['id'] ? 'selected' : '' ?>><?= e($province['name']) ?></option><?php endforeach; ?></select></td><td><input type="number" name="sort_order" value="<?= (int)$city['sort_order'] ?>"></td><td><input type="checkbox" name="is_active" value="1" <?= $city['is_active'] ? 'checked' : '' ?>></td><td><button>Update</button></form><form class="inline" method="post" action="/admin/catalogs/cities/delete" onsubmit="return confirm('Disable this city?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$city['id'] ?>"><button>Disable</button></form></td></tr><?php endforeach; ?></tbody></table></section>
</div>
<section class="card table-wrap"><h2>Provinces/states</h2><table><thead><tr><th>Name</th><th>Country</th><th>Sort</th><th>Active</th><th></th></tr></thead><tbody><?php foreach ($provinces as $province): ?><tr><form method="post" action="/admin/catalogs/provinces"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$province['id'] ?>"><td><input name="name" value="<?= e($province['name']) ?>" required></td><td><input name="country_code" value="<?= e($province['country_code']) ?>" maxlength="2"></td><td><input type="number" name="sort_order" value="<?= (int)$province['sort_order'] ?>"></td><td><input type="checkbox" name="is_active" value="1" <?= $province['is_active'] ? 'checked' : '' ?>></td><td><button>Update</button></form><form class="inline" method="post" action="/admin/catalogs/provinces/delete" onsubmit="return confirm('Disable this province and its cities?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$province['id'] ?>"><button>Disable</button></form></td></tr><?php endforeach; ?></tbody></table></section>
