<h1>هدف‌ها و مکان‌ها</h1>
<div class="grid two">
<section class="card"><h2>افزودن هدف</h2><form method="post" action="/admin/catalogs/goals"><?= csrf_field() ?><label>عنوان <input name="title" required></label><label>توضیح <textarea name="description"></textarea></label><label>ترتیب نمایش <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> فعال</label><button class="button">ذخیره هدف</button></form></section>
<section class="card"><h2>افزودن استان</h2><form method="post" action="/admin/catalogs/provinces"><?= csrf_field() ?><label>نام <input name="name" required></label><label>کد کشور <input name="country_code" value="IR" maxlength="2"></label><label>ترتیب نمایش <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> فعال</label><button class="button">ذخیره استان</button></form></section>
</div>
<section class="card"><h2>افزودن شهر</h2><form method="post" action="/admin/catalogs/cities" class="grid two"><?= csrf_field() ?><label>استان <select name="province_id" required><?php foreach ($provinces as $province): ?><option value="<?= (int)$province['id'] ?>"><?= e($province['name']) ?></option><?php endforeach; ?></select></label><label>نام <input name="name" required></label><label>ترتیب نمایش <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> فعال</label><button class="button">ذخیره شهر</button></form></section>
<div class="grid two">
<section class="card table-wrap"><h2>هدف‌ها</h2><table><thead><tr><th>عنوان</th><th>توضیح</th><th>ترتیب</th><th>فعال</th><th></th></tr></thead><tbody><?php foreach ($goals as $goal): ?><tr><form method="post" action="/admin/catalogs/goals"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$goal['id'] ?>"><td><input name="title" value="<?= e($goal['title']) ?>" required></td><td><input name="description" value="<?= e($goal['description']) ?>"></td><td><input type="number" name="sort_order" value="<?= (int)$goal['sort_order'] ?>"></td><td><input type="checkbox" name="is_active" value="1" <?= $goal['is_active'] ? 'checked' : '' ?>></td><td><button>به‌روزرسانی</button></form><form class="inline" method="post" action="/admin/catalogs/goals/delete" onsubmit="return confirm('این هدف غیرفعال شود؟')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$goal['id'] ?>"><button>غیرفعال‌کردن</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card table-wrap"><h2>شهرها</h2><table><thead><tr><th>شهر</th><th>استان</th><th>ترتیب</th><th>فعال</th><th></th></tr></thead><tbody><?php foreach ($cities as $city): ?><tr><form method="post" action="/admin/catalogs/cities"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$city['id'] ?>"><td><input name="name" value="<?= e($city['name']) ?>" required></td><td><select name="province_id" required><?php foreach ($provinces as $province): ?><option value="<?= (int)$province['id'] ?>" <?= (int)$city['province_id'] === (int)$province['id'] ? 'selected' : '' ?>><?= e($province['name']) ?></option><?php endforeach; ?></select></td><td><input type="number" name="sort_order" value="<?= (int)$city['sort_order'] ?>"></td><td><input type="checkbox" name="is_active" value="1" <?= $city['is_active'] ? 'checked' : '' ?>></td><td><button>به‌روزرسانی</button></form><form class="inline" method="post" action="/admin/catalogs/cities/delete" onsubmit="return confirm('این شهر غیرفعال شود؟')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$city['id'] ?>"><button>غیرفعال‌کردن</button></form></td></tr><?php endforeach; ?></tbody></table></section>
</div>
<section class="card table-wrap"><h2>استان‌ها</h2><table><thead><tr><th>نام</th><th>کشور</th><th>ترتیب</th><th>فعال</th><th></th></tr></thead><tbody><?php foreach ($provinces as $province): ?><tr><form method="post" action="/admin/catalogs/provinces"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$province['id'] ?>"><td><input name="name" value="<?= e($province['name']) ?>" required></td><td><input name="country_code" value="<?= e($province['country_code']) ?>" maxlength="2"></td><td><input type="number" name="sort_order" value="<?= (int)$province['sort_order'] ?>"></td><td><input type="checkbox" name="is_active" value="1" <?= $province['is_active'] ? 'checked' : '' ?>></td><td><button>به‌روزرسانی</button></form><form class="inline" method="post" action="/admin/catalogs/provinces/delete" onsubmit="return confirm('این استان و شهرهای آن غیرفعال شوند؟')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$province['id'] ?>"><button>غیرفعال‌کردن</button></form></td></tr><?php endforeach; ?></tbody></table></section>
