<h1>فرم‌ساز شناخت‌نامه</h1>
<p class="muted">ساختار شناخت‌نامه را به ترتیب مرحله، گروه، پرسش و گزینه مدیریت کنید.</p>
<div class="grid two">
<section class="card"><h2>افزودن مرحله</h2><form method="post" action="/admin/forms/steps"><?= csrf_field() ?><label>عنوان <input name="title" required></label><label>توضیح <textarea name="description"></textarea></label><label>ترتیب نمایش <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> فعال</label><button class="button">ذخیره مرحله</button></form></section>
<section class="card"><h2>افزودن گروه</h2><form method="post" action="/admin/forms/groups"><?= csrf_field() ?><label>مرحله <select name="form_step_id" required><?php foreach ($steps as $step): ?><option value="<?= (int)$step['id'] ?>"><?= e($step['title']) ?></option><?php endforeach; ?></select></label><label>عنوان <input name="title" required></label><label>توضیح <textarea name="description"></textarea></label><label>ترتیب نمایش <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> فعال</label><button class="button">ذخیره گروه</button></form></section>
</div>
<?php $qv = $editingQuestion ?? []; $existingOptions = $existingOptions ?? []; ?>
<section class="card"><div class="section-title"><h2><?= $qv ? 'ویرایش پرسش' : 'ساخت پرسش' ?></h2><?php if ($qv): ?><span class="pill"><?= e($qv['step_title'].' / '.$qv['group_title']) ?></span><?php endif; ?></div>
<form method="post" action="/admin/forms/questions" class="grid three"><?= csrf_field() ?><?php if ($qv): ?><input type="hidden" name="id" value="<?= (int)$qv['id'] ?>"><?php endif; ?>
<div class="builder-section"><h3>اطلاعات پایه</h3><label>گروه <select name="question_group_id" required><?php foreach ($groups as $group): ?><option value="<?= (int)$group['id'] ?>" <?= (int)($qv['question_group_id'] ?? 0) === (int)$group['id'] ? 'selected' : '' ?>><?= e($group['step_title'].' / '.$group['title']) ?></option><?php endforeach; ?></select></label><label>عنوان <input name="title" value="<?= e($qv['title'] ?? '') ?>" required></label><label>توضیح <textarea name="description"><?= e($qv['description'] ?? '') ?></textarea></label><label>متن کمک <textarea name="help_text"><?= e($qv['help_text'] ?? '') ?></textarea></label></div>
<div class="builder-section"><h3>نوع پاسخ</h3><label>نوع پاسخ <select name="answer_type" id="answer-type"><?php foreach ($types as $type): ?><option value="<?= e($type) ?>" <?= ($qv['answer_type'] ?? '') === $type ? 'selected' : '' ?>><?= e(fa_label($type)) ?></option><?php endforeach; ?></select></label><p class="help">برای پاسخ‌های انتخابی گزینه اختصاصی تعریف کنید. نوع‌های شهر از فهرست شهرهای پایگاه داده استفاده می‌کنند.</p><label>متن راهنما <input name="placeholder" value="<?= e($qv['placeholder'] ?? '') ?>"></label><label>ترتیب نمایش <input type="number" name="sort_order" value="<?= e((string)($qv['sort_order'] ?? '0')) ?>"></label><label class="check"><input type="checkbox" name="is_required" value="1" <?= !empty($qv['is_required']) ? 'checked' : '' ?>> پاسخ ضروری است</label><label class="check"><input type="checkbox" name="is_active" value="1" <?= !array_key_exists('is_active', $qv) || !empty($qv['is_active']) ? 'checked' : '' ?>> فعال</label></div>
<div class="builder-section"><h3>حریم خصوصی</h3><label>قابل اعمال برای <input name="applies_to" value="<?= e($qv['applies_to'] ?? 'all') ?>"></label><p class="help">معمولاً مقدار all را نگه دارید مگر پرسش برای گروه خاصی از اعضا باشد.</p><label>محدوده نمایش <select name="visibility_scope"><?php foreach (['private','matches','admins','public'] as $scope): ?><option value="<?= e($scope) ?>" <?= ($qv['visibility_scope'] ?? 'private') === $scope ? 'selected' : '' ?>><?= e(fa_label($scope)) ?></option><?php endforeach; ?></select></label><label>سطح حساسیت <select name="privacy_level"><?php foreach (['low','medium','high'] as $level): ?><option value="<?= e($level) ?>" <?= ($qv['privacy_level'] ?? 'medium') === $level ? 'selected' : '' ?>><?= e(fa_label($level)) ?></option><?php endforeach; ?></select></label><p class="help">پاسخ‌های حساس بهتر است خصوصی یا ویژه مدیران بمانند، مگر اینکه آگاهانه برای کارت معرفی انتخاب شوند.</p><label class="check"><input type="checkbox" name="is_sensitive" value="1" <?= !empty($qv['is_sensitive']) ? 'checked' : '' ?>> حساس</label></div>
<div class="builder-section"><h3>سازگاری</h3><label class="check"><input type="checkbox" name="is_matchable" value="1" <?= !empty($qv['is_matchable']) ? 'checked' : '' ?>> در محاسبه سازگاری استفاده شود</label><label>قاعده سازگاری <input name="match_rule" value="<?= e($qv['match_rule'] ?? 'exact') ?>"></label><p class="help">نمونه مقدارها: exact، overlap، near، range_overlap، distance.</p><label>وزن سازگاری <input type="number" step="0.01" name="match_weight" value="<?= e((string)($qv['match_weight'] ?? '1')) ?>"></label></div>
<div class="builder-section"><h3>کارت معرفی</h3><label class="check"><input type="checkbox" name="show_in_match_card" value="1" <?= !empty($qv['show_in_match_card']) ? 'checked' : '' ?>> در کارت معرفی نمایش داده شود</label><label>اولویت نمایش در کارت <input type="number" name="match_card_priority" value="<?= e((string)($qv['match_card_priority'] ?? '0')) ?>"></label><p class="help">موارد با اولویت پایین‌تر در کارت‌های فشرده زودتر پنهان می‌شوند.</p></div>
<div class="builder-section"><h3>اعتبارسنجی و رابط</h3><p class="help">پرسش ضروری را با احتیاط استفاده کنید. پرسش‌های حساس را خصوصی نگه دارید. مقدار گزینه‌ها را پایدار نگه دارید چون ممکن است در سازگاری استفاده شوند.</p></div>
<div class="full builder-section" id="option-editor"><h3>گزینه‌ها</h3><p class="help">فقط برای نوع‌های انتخابی نمایش داده می‌شود. ردیف‌های حذف‌شده نرم‌غیرفعال می‌شوند تا پاسخ‌های قبلی حفظ شوند.</p><?php for ($i=0; $i<max(6, count($existingOptions)+1); $i++): ?><?php $opt = $existingOptions[$i] ?? []; ?><div class="option-row"><?php if (!empty($opt['id'])): ?><input type="hidden" name="options[<?= $i ?>][id]" value="<?= (int)$opt['id'] ?>"><?php endif; ?><span class="pill">#<?= $i+1 ?></span><input name="options[<?= $i ?>][label]" placeholder="عنوان" value="<?= e($opt['label'] ?? '') ?>"><input name="options[<?= $i ?>][value]" placeholder="مقدار" value="<?= e($opt['value'] ?? '') ?>"><input name="options[<?= $i ?>][description]" placeholder="توضیح" value="<?= e($opt['description'] ?? '') ?>"><input type="number" name="options[<?= $i ?>][sort_order]" value="<?= e((string)($opt['sort_order'] ?? (($i+1)*10))) ?>"><label><input type="checkbox" name="options[<?= $i ?>][is_active]" value="1" <?= !array_key_exists('is_active', $opt) || !empty($opt['is_active']) ? 'checked' : '' ?>> فعال</label><small><?= !empty($opt['answer_count']) ? e($opt['answer_count'].' پاسخ موجود') : 'بدون پاسخ' ?></small></div><?php endfor; ?></div>
<div class="full"><button class="button">ذخیره پرسش</button><?php if ($qv): ?><a class="button secondary" href="/admin/forms">لغو ویرایش</a><?php endif; ?></div></form></section>
<section class="card table-wrap"><h2>مرحله‌ها</h2><table><thead><tr><th>عنوان</th><th>ترتیب</th><th>فعال</th><th></th></tr></thead><tbody><?php foreach ($steps as $step): ?><tr><td><?= e($step['title']) ?></td><td><?= (int)$step['sort_order'] ?></td><td><?= $step['is_active'] ? 'بله' : 'خیر' ?></td><td><form class="inline" method="post" action="/admin/forms/steps/delete" onsubmit="return confirm('این مرحله غیرفعال شود؟')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$step['id'] ?>"><button>غیرفعال‌کردن</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card table-wrap"><h2>گروه‌ها</h2><table><thead><tr><th>مرحله</th><th>عنوان</th><th>ترتیب</th><th>فعال</th><th></th></tr></thead><tbody><?php foreach ($groups as $group): ?><tr><td><?= e($group['step_title']) ?></td><td><?= e($group['title']) ?></td><td><?= (int)$group['sort_order'] ?></td><td><?= $group['is_active'] ? 'بله' : 'خیر' ?></td><td><form class="inline" method="post" action="/admin/forms/groups/delete" onsubmit="return confirm('این گروه غیرفعال شود؟')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$group['id'] ?>"><button>غیرفعال‌کردن</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card table-wrap"><h2>پرسش‌ها</h2><table><thead><tr><th>گروه</th><th>عنوان</th><th>نوع</th><th>حریم خصوصی</th><th>سازگاری</th><th>فعال</th><th></th></tr></thead><tbody><?php foreach ($questions as $q): ?><tr><td><?= e($q['group_title']) ?></td><td><?= e($q['title']) ?></td><td><?= e(fa_label($q['answer_type'])) ?></td><td><?= e(fa_label($q['privacy_level'])) ?></td><td><?= $q['is_matchable'] ? 'بله' : 'خیر' ?></td><td><?= $q['is_active'] ? 'بله' : 'خیر' ?></td><td><a href="/admin/forms?edit=<?= (int)$q['id'] ?>">ویرایش</a><form class="inline" method="post" action="/admin/forms/questions/delete" onsubmit="return confirm('این پرسش غیرفعال شود؟')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$q['id'] ?>"><button>غیرفعال‌کردن</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<script>
(function(){
  var type = document.getElementById('answer-type');
  var editor = document.getElementById('option-editor');
  var choiceTypes = ['single_choice','multi_choice','select','multi_select'];
  function sync(){ editor.classList.toggle('hidden', choiceTypes.indexOf(type.value) === -1); }
  if(type && editor){ type.addEventListener('change', sync); sync(); }
})();
</script>
