<h1>Dynamic form builder</h1>
<div class="grid two">
<section class="card"><h2>Add step</h2><form method="post" action="/admin/forms/steps"><?= csrf_field() ?><label>Title <input name="title" required></label><label>Description <textarea name="description"></textarea></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save step</button></form></section>
<section class="card"><h2>Add group</h2><form method="post" action="/admin/forms/groups"><?= csrf_field() ?><label>Step <select name="form_step_id" required><?php foreach ($steps as $step): ?><option value="<?= (int)$step['id'] ?>"><?= e($step['title']) ?></option><?php endforeach; ?></select></label><label>Title <input name="title" required></label><label>Description <textarea name="description"></textarea></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save group</button></form></section>
</div>
<?php $qv = $editQuestion ?? []; $existingOptions = $qv['options'] ?? []; ?>
<section class="card"><h2><?= $qv ? 'Edit question' : 'Add question' ?></h2><form method="post" action="/admin/forms/questions" class="grid two"><?= csrf_field() ?><?php if ($qv): ?><input type="hidden" name="id" value="<?= (int)$qv['id'] ?>"><?php endif; ?>
<label>Group <select name="question_group_id" required><?php foreach ($groups as $group): ?><option value="<?= (int)$group['id'] ?>" <?= (int)($qv['question_group_id'] ?? 0) === (int)$group['id'] ? 'selected' : '' ?>><?= e($group['step_title'].' / '.$group['title']) ?></option><?php endforeach; ?></select></label>
<label>Title <input name="title" value="<?= e($qv['title'] ?? '') ?>" required></label><label>Description <textarea name="description"><?= e($qv['description'] ?? '') ?></textarea></label><label>Help text <textarea name="help_text"><?= e($qv['help_text'] ?? '') ?></textarea></label><label>Placeholder <input name="placeholder" value="<?= e($qv['placeholder'] ?? '') ?>"></label>
<label>Answer type <select name="answer_type"><?php foreach ($types as $type): ?><option value="<?= e($type) ?>" <?= ($qv['answer_type'] ?? '') === $type ? 'selected' : '' ?>><?= e($type) ?></option><?php endforeach; ?></select></label>
<label>Applies to <input name="applies_to" value="<?= e($qv['applies_to'] ?? 'all') ?>"></label><label>Visibility <select name="visibility_scope"><?php foreach (['private','matches','admins','public'] as $scope): ?><option <?= ($qv['visibility_scope'] ?? 'private') === $scope ? 'selected' : '' ?>><?= e($scope) ?></option><?php endforeach; ?></select></label>
<label>Privacy level <select name="privacy_level"><?php foreach (['low','medium','high'] as $level): ?><option <?= ($qv['privacy_level'] ?? 'medium') === $level ? 'selected' : '' ?>><?= e($level) ?></option><?php endforeach; ?></select></label><label>Match rule <input name="match_rule" value="<?= e($qv['match_rule'] ?? 'exact') ?>"></label><label>Match weight <input type="number" step="0.01" name="match_weight" value="<?= e((string)($qv['match_weight'] ?? '1')) ?>"></label><label>Match card priority <input type="number" name="match_card_priority" value="<?= e((string)($qv['match_card_priority'] ?? '0')) ?>"></label><label>Sort order <input type="number" name="sort_order" value="<?= e((string)($qv['sort_order'] ?? '0')) ?>"></label>
<div class="full checks"><label><input type="checkbox" name="is_required" value="1" <?= !empty($qv['is_required']) ? 'checked' : '' ?>> Required</label><label><input type="checkbox" name="is_active" value="1" <?= !array_key_exists('is_active', $qv) || !empty($qv['is_active']) ? 'checked' : '' ?>> Active</label><label><input type="checkbox" name="is_sensitive" value="1" <?= !empty($qv['is_sensitive']) ? 'checked' : '' ?>> Sensitive</label><label><input type="checkbox" name="show_in_match_card" value="1" <?= !empty($qv['show_in_match_card']) ? 'checked' : '' ?>> Show in match card</label><label><input type="checkbox" name="is_matchable" value="1" <?= !empty($qv['is_matchable']) ? 'checked' : '' ?>> Matchable</label></div>
<div class="full"><h3>Options for choice/select questions</h3><?php for ($i=0; $i<max(5, count($existingOptions)); $i++): $opt = $existingOptions[$i] ?? []; ?><div class="option-row"><input name="options[<?= $i ?>][label]" placeholder="Label" value="<?= e($opt['label'] ?? '') ?>"><input name="options[<?= $i ?>][value]" placeholder="Value" value="<?= e($opt['value'] ?? '') ?>"><input type="number" name="options[<?= $i ?>][sort_order]" value="<?= e((string)($opt['sort_order'] ?? (($i+1)*10))) ?>"><label><input type="checkbox" name="options[<?= $i ?>][is_active]" value="1" <?= !array_key_exists('is_active', $opt) || !empty($opt['is_active']) ? 'checked' : '' ?>> Active</label></div><?php endfor; ?></div>
<button class="button">Save question</button><?php if ($qv): ?><a class="button secondary" href="/admin/forms">Cancel edit</a><?php endif; ?></form></section>
<section class="card table-wrap"><h2>Existing questions</h2><table><thead><tr><th>Group</th><th>Title</th><th>Type</th><th>Required</th><th>Active</th><th>Actions</th></tr></thead><tbody><?php foreach ($questions as $q): ?><tr><td><?= e($q['group_title']) ?></td><td><?= e($q['title']) ?></td><td><?= e($q['answer_type']) ?></td><td><?= $q['is_required'] ? 'Yes' : 'No' ?></td><td><?= $q['is_active'] ? 'Yes' : 'No' ?></td><td><a href="/admin/forms?edit=<?= (int)$q['id'] ?>">Edit</a><form class="inline" method="post" action="/admin/forms/questions/delete" onsubmit="return confirm('Delete this question?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$q['id'] ?>"><button>Delete</button></form></td></tr><?php endforeach; ?></tbody></table></section>
