<h1>Dynamic form builder</h1>
<p class="muted">Create the onboarding structure in order: steps → groups → questions → options.</p>
<div class="grid two">
<section class="card"><h2>Add step</h2><form method="post" action="/admin/forms/steps"><?= csrf_field() ?><label>Title <input name="title" required></label><label>Description <textarea name="description"></textarea></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save step</button></form></section>
<section class="card"><h2>Add group</h2><form method="post" action="/admin/forms/groups"><?= csrf_field() ?><label>Step <select name="form_step_id" required><?php foreach ($steps as $step): ?><option value="<?= (int)$step['id'] ?>"><?= e($step['title']) ?></option><?php endforeach; ?></select></label><label>Title <input name="title" required></label><label>Description <textarea name="description"></textarea></label><label>Sort order <input type="number" name="sort_order" value="0"></label><label class="check"><input type="checkbox" name="is_active" value="1" checked> Active</label><button class="button">Save group</button></form></section>
</div>
<?php $qv = $editQuestion ?? []; $existingOptions = $qv['options'] ?? []; $choiceTypes = ['single_choice','multi_choice','select','multi_select']; ?>
<section class="card"><div class="section-title"><h2><?= $qv ? 'Edit question' : 'Create question' ?></h2><?php if ($qv): ?><span class="pill"><?= e($qv['step_title'].' / '.$qv['group_title']) ?></span><?php endif; ?></div>
<form method="post" action="/admin/forms/questions" class="grid two" id="question-form"><?= csrf_field() ?><?php if ($qv): ?><input type="hidden" name="id" value="<?= (int)$qv['id'] ?>"><?php endif; ?>
<div class="builder-section"><h3>Basic Info</h3><label>Group <select name="question_group_id" required><?php foreach ($groups as $group): ?><option value="<?= (int)$group['id'] ?>" <?= (int)($qv['question_group_id'] ?? 0) === (int)$group['id'] ? 'selected' : '' ?>><?= e($group['step_title'].' / '.$group['title']) ?></option><?php endforeach; ?></select></label><label>Title <input name="title" value="<?= e($qv['title'] ?? '') ?>" required></label><label>Description <textarea name="description"><?= e($qv['description'] ?? '') ?></textarea></label><label>Help text <textarea name="help_text"><?= e($qv['help_text'] ?? '') ?></textarea></label></div>
<div class="builder-section"><h3>Answer Type</h3><label>Answer type <select name="answer_type" id="answer-type"><?php foreach ($types as $type): ?><option value="<?= e($type) ?>" <?= ($qv['answer_type'] ?? '') === $type ? 'selected' : '' ?>><?= e($type) ?></option><?php endforeach; ?></select></label><p class="help">Choice/select types use custom options. City types use database cities; do not add custom options.</p><label>Placeholder <input name="placeholder" value="<?= e($qv['placeholder'] ?? '') ?>"></label><label>Sort order <input type="number" name="sort_order" value="<?= e((string)($qv['sort_order'] ?? '0')) ?>"></label><label class="check"><input type="checkbox" name="is_required" value="1" <?= !empty($qv['is_required']) ? 'checked' : '' ?>> Required answer</label><label class="check"><input type="checkbox" name="is_active" value="1" <?= !array_key_exists('is_active', $qv) || !empty($qv['is_active']) ? 'checked' : '' ?>> Active</label></div>
<div class="builder-section"><h3>Privacy</h3><label>Applies to <input name="applies_to" value="<?= e($qv['applies_to'] ?? 'all') ?>"></label><p class="help">Use all unless a question should apply to a specific member segment.</p><label>Visibility <select name="visibility_scope"><?php foreach (['private','matches','admins','public'] as $scope): ?><option <?= ($qv['visibility_scope'] ?? 'private') === $scope ? 'selected' : '' ?>><?= e($scope) ?></option><?php endforeach; ?></select></label><label>Privacy level <select name="privacy_level"><?php foreach (['low','medium','high'] as $level): ?><option <?= ($qv['privacy_level'] ?? 'medium') === $level ? 'selected' : '' ?>><?= e($level) ?></option><?php endforeach; ?></select></label><p class="help">High privacy answers should remain admin/private unless intentionally shown.</p><label class="check"><input type="checkbox" name="is_sensitive" value="1" <?= !empty($qv['is_sensitive']) ? 'checked' : '' ?>> Sensitive</label></div>
<div class="builder-section"><h3>Matching</h3><label class="check"><input type="checkbox" name="is_matchable" value="1" <?= !empty($qv['is_matchable']) ? 'checked' : '' ?>> Use for compatibility later</label><label>Match rule <input name="match_rule" value="<?= e($qv['match_rule'] ?? 'exact') ?>"></label><p class="help">Examples: exact, overlap, near, range_overlap, distance. Matching is not implemented yet.</p><label>Match weight <input type="number" step="0.01" name="match_weight" value="<?= e((string)($qv['match_weight'] ?? '1')) ?>"></label></div>
<div class="builder-section"><h3>Match Card</h3><label class="check"><input type="checkbox" name="show_in_match_card" value="1" <?= !empty($qv['show_in_match_card']) ? 'checked' : '' ?>> Show on future match card</label><label>Match card priority <input type="number" name="match_card_priority" value="<?= e((string)($qv['match_card_priority'] ?? '0')) ?>"></label><p class="help">Lower priority items can be hidden first in compact cards.</p></div>
<div class="builder-section"><h3>Validation/UI</h3><p class="help">Use required sparingly. Keep sensitive questions private. For choice questions, keep stable option values because they may be used by future compatibility logic.</p></div>
<div class="full builder-section" id="option-editor"><h3>Options</h3><p class="help">Only shown for single/multi choice and select types. Removed rows are soft-disabled to preserve existing answers.</p><?php for ($i=0; $i<max(6, count($existingOptions)+1); $i++): ?><?php $opt = $existingOptions[$i] ?? []; ?><div class="option-row"><?php if (!empty($opt['id'])): ?><input type="hidden" name="options[<?= $i ?>][id]" value="<?= (int)$opt['id'] ?>"><?php endif; ?><span class="pill">#<?= $i+1 ?></span><input name="options[<?= $i ?>][label]" placeholder="Title" value="<?= e($opt['label'] ?? '') ?>"><input name="options[<?= $i ?>][value]" placeholder="Value" value="<?= e($opt['value'] ?? '') ?>"><input name="options[<?= $i ?>][description]" placeholder="Description" value="<?= e($opt['description'] ?? '') ?>"><input type="number" name="options[<?= $i ?>][sort_order]" value="<?= e((string)($opt['sort_order'] ?? (($i+1)*10))) ?>"><label><input type="checkbox" name="options[<?= $i ?>][is_active]" value="1" <?= !array_key_exists('is_active', $opt) || !empty($opt['is_active']) ? 'checked' : '' ?>> Active</label><small><?= !empty($opt['answer_count']) ? e($opt['answer_count'].' existing answers') : 'No answers' ?></small></div><?php endfor; ?></div>
<div class="full"><button class="button">Save question</button><?php if ($qv): ?><a class="button secondary" href="/admin/forms">Cancel edit</a><?php endif; ?></div></form></section>
<section class="card table-wrap"><h2>Steps</h2><table><thead><tr><th>Title</th><th>Sort</th><th>Active</th><th></th></tr></thead><tbody><?php foreach ($steps as $step): ?><tr><td><?= e($step['title']) ?></td><td><?= (int)$step['sort_order'] ?></td><td><?= $step['is_active'] ? 'Yes' : 'No' ?></td><td><form class="inline" method="post" action="/admin/forms/steps/delete" onsubmit="return confirm('Disable this step?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$step['id'] ?>"><button>Disable</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card table-wrap"><h2>Groups</h2><table><thead><tr><th>Step</th><th>Title</th><th>Sort</th><th>Active</th><th></th></tr></thead><tbody><?php foreach ($groups as $group): ?><tr><td><?= e($group['step_title']) ?></td><td><?= e($group['title']) ?></td><td><?= (int)$group['sort_order'] ?></td><td><?= $group['is_active'] ? 'Yes' : 'No' ?></td><td><form class="inline" method="post" action="/admin/forms/groups/delete" onsubmit="return confirm('Disable this group?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$group['id'] ?>"><button>Disable</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card table-wrap"><h2>Questions</h2><table><thead><tr><th>Group</th><th>Title</th><th>Type</th><th>Privacy</th><th>Matchable</th><th>Active</th><th></th></tr></thead><tbody><?php foreach ($questions as $q): ?><tr><td><?= e($q['group_title']) ?></td><td><?= e($q['title']) ?></td><td><?= e($q['answer_type']) ?></td><td><?= e($q['privacy_level']) ?></td><td><?= $q['is_matchable'] ? 'Yes' : 'No' ?></td><td><?= $q['is_active'] ? 'Yes' : 'No' ?></td><td><a href="/admin/forms?edit=<?= (int)$q['id'] ?>">Edit</a><form class="inline" method="post" action="/admin/forms/questions/delete" onsubmit="return confirm('Disable this question?')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$q['id'] ?>"><button>Disable</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<script>
(function(){
  var type = document.getElementById('answer-type');
  var editor = document.getElementById('option-editor');
  var choiceTypes = ['single_choice','multi_choice','select','multi_select'];
  function sync(){ editor.classList.toggle('hidden', choiceTypes.indexOf(type.value) === -1); }
  if(type && editor){ type.addEventListener('change', sync); sync(); }
})();
</script>
