<?php
require dirname(__DIR__) . '/src/bootstrap.php';

use App\Core\Router;
use App\Controllers\AdminController;
use App\Controllers\AuthController;
use App\Controllers\HomeController;
use App\Controllers\ChatController;
use App\Controllers\MatchController;
use App\Controllers\ReportController;
use App\Controllers\SafetyController;
use App\Controllers\SupportController;
use App\Controllers\OnboardingController;

$router = new Router();
$router->get('/', [HomeController::class, 'index']);
$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/register', [AuthController::class, 'showRegister']);
$router->post('/register', [AuthController::class, 'register']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->get('/matches', [MatchController::class, 'index']);
$router->post('/matches/action', [MatchController::class, 'action']);
$router->get('/chats', [ChatController::class, 'index']);
$router->get('/chats/{id}', [ChatController::class, 'show']);
$router->post('/chats/{id}/messages', [ChatController::class, 'send']);
$router->post('/chats/{id}/reveal-requests', [ChatController::class, 'requestReveal']);
$router->post('/chats/reveal-requests/respond', [ChatController::class, 'respondReveal']);
$router->post('/chats/messages/flag', [ChatController::class, 'flagMessage']);
$router->post('/reports/match', [ReportController::class, 'match']);
$router->post('/reports/chat', [ReportController::class, 'chat']);
$router->post('/reports/message', [ReportController::class, 'message']);
$router->get('/safety', [SafetyController::class, 'index']);
$router->post('/safety/unblock', [SafetyController::class, 'unblock']);
$router->get('/safety/privacy-shield', [SafetyController::class, 'privacyShield']);
$router->post('/safety/privacy-shield', [SafetyController::class, 'addPrivacyShield']);
$router->post('/safety/privacy-shield/delete', [SafetyController::class, 'deletePrivacyShield']);
$router->get('/support', [SupportController::class, 'index']);
$router->post('/support', [SupportController::class, 'create']);
$router->get('/support/{id}', [SupportController::class, 'show']);
$router->post('/support/{id}/messages', [SupportController::class, 'send']);
$router->get('/onboarding', [OnboardingController::class, 'show']);
$router->post('/onboarding', [OnboardingController::class, 'save']);
$router->get('/admin', [AdminController::class, 'dashboard']);
$router->get('/admin/forms', [AdminController::class, 'formBuilder']);
$router->post('/admin/forms/steps', [AdminController::class, 'saveStep']);
$router->post('/admin/forms/steps/delete', [AdminController::class, 'deleteStep']);
$router->post('/admin/forms/groups', [AdminController::class, 'saveGroup']);
$router->post('/admin/forms/groups/delete', [AdminController::class, 'deleteGroup']);
$router->post('/admin/forms/questions', [AdminController::class, 'saveQuestion']);
$router->post('/admin/forms/questions/delete', [AdminController::class, 'deleteQuestion']);
$router->get('/admin/catalogs', [AdminController::class, 'catalogs']);
$router->post('/admin/catalogs/goals', [AdminController::class, 'saveGoal']);
$router->post('/admin/catalogs/goals/delete', [AdminController::class, 'deleteGoal']);
$router->post('/admin/catalogs/provinces', [AdminController::class, 'saveProvince']);
$router->post('/admin/catalogs/provinces/delete', [AdminController::class, 'deleteProvince']);
$router->post('/admin/catalogs/cities', [AdminController::class, 'saveCity']);
$router->post('/admin/catalogs/cities/delete', [AdminController::class, 'deleteCity']);
$router->get('/admin/health', [AdminController::class, 'health']);
$router->get('/admin/intelligence', [AdminController::class, 'intelligence']);
$router->get('/admin/safety/privacy-shields', [AdminController::class, 'privacyShields']);
$router->get('/admin/safety/diagnostics', [AdminController::class, 'safetyDiagnostics']);
$router->get('/admin/support', [AdminController::class, 'supportCenter']);
$router->post('/admin/support/assign', [AdminController::class, 'assignSupport']);
$router->post('/admin/support/close', [AdminController::class, 'closeSupport']);
$router->post('/admin/support/quick-replies', [AdminController::class, 'saveQuickReply']);
$router->post('/admin/support/quick-replies/delete', [AdminController::class, 'deleteQuickReply']);
$router->post('/admin/support/archive', [AdminController::class, 'archiveSupport']);
$router->post('/admin/support/reopen', [AdminController::class, 'reopenSupport']);
$router->get('/admin/matches', [AdminController::class, 'matches']);
$router->post('/admin/matches/run', [AdminController::class, 'runMatching']);
$router->post('/admin/matches/reset', [AdminController::class, 'resetMatch']);
$router->post('/admin/matches/recalculate', [AdminController::class, 'recalculateMatch']);
$router->get('/admin/chats', [AdminController::class, 'chats']);
$router->get('/admin/chats/{id}', [AdminController::class, 'chatDetail']);
$router->post('/admin/chats/{id}/close', [AdminController::class, 'closeChat']);
$router->get('/admin/reveals', [AdminController::class, 'reveals']);
$router->post('/admin/reveals/types', [AdminController::class, 'saveRevealType']);
$router->get('/admin/moderation', [AdminController::class, 'moderation']);
$router->get('/admin/moderation/{id}', [AdminController::class, 'reportDetail']);
$router->post('/admin/moderation/{id}', [AdminController::class, 'updateReport']);
$router->post('/admin/moderation/{id}/block', [AdminController::class, 'blockFromReport']);
$router->get('/admin/settings', [AdminController::class, 'settings']);
$router->post('/admin/settings', [AdminController::class, 'saveSettings']);
$router->get('/admin/users', [AdminController::class, 'users']);
$router->get('/admin/users/show', [AdminController::class, 'userDetail']);
$router->dispatch($_SERVER['REQUEST_METHOD'], $_SERVER['REQUEST_URI']);
